In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("train.csv", index_col=0)
print(df.columns)
df = df.drop(["Cabin","Name","Ticket"], axis=1)
df

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

             Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
PassengerId
1                   0       3    male  22.0      1      0   7.2500        S
2                   1       1  female  38.0      1      0  71.2833        C
3                   1       3  female  26.0      0      0   7.9250        S
4                   1       1  female  35.0      1      0  53.1000        S
5                   0       3    male  35.0      0      0   8.0500        S
...               ...     ...     ...   ...    ...    ...      ...      ...
887                 0       2    male  27.0      0      0  13.0000        S
888                 1       1  female  19.0      0      0  30.0000        S
889                 0       3  female   NaN      1      2  23.4500        S
890                 1       1    male  26.0      0      0  30.0000        C
891                 0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [3]:
df1 = df["Sex"]
df_dummy = pd.get_dummies(df1,drop_first=True)
df["Sex_M"] = df_dummy #Male is one
df = df.drop(columns=["Sex"])
df

             Survived  Pclass   Age  SibSp  Parch     Fare Embarked  Sex_M
PassengerId
1                   0       3  22.0      1      0   7.2500        S      1
2                   1       1  38.0      1      0  71.2833        C      0
3                   1       3  26.0      0      0   7.9250        S      0
4                   1       1  35.0      1      0  53.1000        S      0
5                   0       3  35.0      0      0   8.0500        S      1
...               ...     ...   ...    ...    ...      ...      ...    ...
887                 0       2  27.0      0      0  13.0000        S      1
888                 1       1  19.0      0      0  30.0000        S      0
889                 0       3   NaN      1      2  23.4500        S      0
890                 1       1  26.0      0      0  30.0000        C      1
891                 0       3  32.0      0      0   7.7500        Q      1

[891 rows x 8 columns]

In [4]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
Sex_M         0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
df = df.apply(lambda col: LabelEncoder().fit_transform(df["Embarked"]) if col.dtype == "object" else col)
df.head(15)

             Survived  Pclass   Age  SibSp  Parch     Fare  Embarked  Sex_M
PassengerId
1                   0       3  22.0      1      0   7.2500         2      1
2                   1       1  38.0      1      0  71.2833         0      0
3                   1       3  26.0      0      0   7.9250         2      0
4                   1       1  35.0      1      0  53.1000         2      0
5                   0       3  35.0      0      0   8.0500         2      1
6                   0       3   NaN      0      0   8.4583         1      1
7                   0       1  54.0      0      0  51.8625         2      1
8                   0       3   2.0      3      1  21.0750         2      1
9                   1       3  27.0      0      2  11.1333         2      0
10                  1       2  14.0      1      0  30.0708         0      0
11                  1       3   4.0      1      1  16.7000         2      0
12                  1       1  58.0      0      0  26.5500         2      0
13                  0       3  20.0      0      0   8.0500         2      1
14                  0       3  39.0      1      5  31.2750         2      1
15                  0       3  14.0      0      0   7.8542         2      0

In [6]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      0
Sex_M         0
dtype: int64

In [7]:
from numpy import isnan
from sklearn.impute import KNNImputer
# split into input and output elements
data = df.values
ix = [i for i in range(data.shape[1]) if i != 9]
X, y = data[:, ix], data[:, 7]
# print total missing
print('Missing: %d' % sum(isnan(X).flatten()))
# define imputer
imputer = KNNImputer()
# fit on the dataset
imputer.fit(X)
# transform the dataset
df = imputer.transform(X)
# print total missing
print('Missing: %d' % sum(isnan(df).flatten()))

Missing: 177
Missing: 0

In [8]:
df = pd.DataFrame(df)
df.columns = ["Survived","Pclass","Age","SibSp","Parch","Fare","Embarked","Sex_M"]
df

     Survived  Pclass   Age  SibSp  Parch     Fare  Embarked  Sex_M
0         0.0     3.0  22.0    1.0    0.0   7.2500       2.0    1.0
1         1.0     1.0  38.0    1.0    0.0  71.2833       0.0    0.0
2         1.0     3.0  26.0    0.0    0.0   7.9250       2.0    0.0
3         1.0     1.0  35.0    1.0    0.0  53.1000       2.0    0.0
4         0.0     3.0  35.0    0.0    0.0   8.0500       2.0    1.0
..        ...     ...   ...    ...    ...      ...       ...    ...
886       0.0     2.0  27.0    0.0    0.0  13.0000       2.0    1.0
887       1.0     1.0  19.0    0.0    0.0  30.0000       2.0    0.0
888       0.0     3.0  26.8    1.0    2.0  23.4500       2.0    0.0
889       1.0     1.0  26.0    0.0    0.0  30.0000       0.0    1.0
890       0.0     3.0  32.0    0.0    0.0   7.7500       1.0    1.0

[891 rows x 8 columns]

In [9]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Sex_M       0
dtype: int64

In [10]:
le = LabelEncoder()
df['Embarked'] = le.fit_transform(df['Embarked'])
df

     Survived  Pclass   Age  SibSp  Parch     Fare  Embarked  Sex_M
0         0.0     3.0  22.0    1.0    0.0   7.2500         2    1.0
1         1.0     1.0  38.0    1.0    0.0  71.2833         0    0.0
2         1.0     3.0  26.0    0.0    0.0   7.9250         2    0.0
3         1.0     1.0  35.0    1.0    0.0  53.1000         2    0.0
4         0.0     3.0  35.0    0.0    0.0   8.0500         2    1.0
..        ...     ...   ...    ...    ...      ...       ...    ...
886       0.0     2.0  27.0    0.0    0.0  13.0000         2    1.0
887       1.0     1.0  19.0    0.0    0.0  30.0000         2    0.0
888       0.0     3.0  26.8    1.0    2.0  23.4500         2    0.0
889       1.0     1.0  26.0    0.0    0.0  30.0000         0    1.0
890       0.0     3.0  32.0    0.0    0.0   7.7500         1    1.0

[891 rows x 8 columns]

In [11]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Sex_M       0
dtype: int64

In [12]:
X = df[["Pclass","Age","SibSp","Parch","Fare","Embarked","Sex_M"]]
X

     Pclass   Age  SibSp  Parch     Fare  Embarked  Sex_M
0       3.0  22.0    1.0    0.0   7.2500         2    1.0
1       1.0  38.0    1.0    0.0  71.2833         0    0.0
2       3.0  26.0    0.0    0.0   7.9250         2    0.0
3       1.0  35.0    1.0    0.0  53.1000         2    0.0
4       3.0  35.0    0.0    0.0   8.0500         2    1.0
..      ...   ...    ...    ...      ...       ...    ...
886     2.0  27.0    0.0    0.0  13.0000         2    1.0
887     1.0  19.0    0.0    0.0  30.0000         2    0.0
888     3.0  26.8    1.0    2.0  23.4500         2    0.0
889     1.0  26.0    0.0    0.0  30.0000         0    1.0
890     3.0  32.0    0.0    0.0   7.7500         1    1.0

[891 rows x 7 columns]

In [13]:
y = df[["Survived"]]
y

     Survived
0         0.0
1         1.0
2         1.0
3         1.0
4         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[891 rows x 1 columns]

In [14]:
from sklearn.model_selection import train_test_split
#split dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=262)
X_train

     Pclass   Age  SibSp  Parch     Fare  Embarked  Sex_M
259     2.0  50.0    0.0    1.0  26.0000         2    0.0
123     2.0  32.5    0.0    0.0  13.0000         2    0.0
452     1.0  30.0    0.0    0.0  27.7500         0    1.0
642     3.0   2.0    3.0    2.0  27.9000         2    0.0
336     1.0  29.0    1.0    0.0  66.6000         2    1.0
..      ...   ...    ...    ...      ...       ...    ...
339     1.0  45.0    0.0    0.0  35.5000         2    1.0
591     1.0  52.0    1.0    0.0  78.2667         0    0.0
558     1.0  39.0    1.0    1.0  79.6500         2    0.0
854     2.0  44.0    1.0    0.0  26.0000         2    0.0
717     2.0  27.0    0.0    0.0  10.5000         2    0.0

[757 rows x 7 columns]

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_test

array([[ 8.39521302e-01, -9.48596484e-01,  3.22414704e+00,
         1.98322418e+00, -4.90485016e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -1.02159175e+00, -4.79463445e-01,
        -4.81965811e-01, -4.65590140e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -2.91639120e-01,  4.46439177e-01,
        -4.81965811e-01, -3.64648038e-01, -1.91989383e+00,
         7.44590347e-01],
       [ 8.39521302e-01, -7.99528586e-02, -4.79463445e-01,
        -4.81965811e-01, -3.44492382e-01, -6.64833700e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  3.79917296e-01,  6.92775753e+00,
         1.98322418e+00,  6.97210836e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -5.10624908e-01, -4.79463445e-01,
        -4.81965811e-01, -4.40857157e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -4.37629646e-01,  4.46439177e-01,
        -4.81965811e-01, -3.32928609e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  1.46024718e+00, -4.79463445e-01,
        -4.81965811e-01, -8.98484642e-02, -1.91989383e+00,
        -1.34302037e+00],
       [ 8.39521302e-01, -5.10624908e-01, -4.79463445e-01,
        -4.81965811e-01, -4.65430175e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  2.33926771e-01, -4.79463445e-01,
        -4.81965811e-01, -4.97712374e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  9.49280345e-01,  4.46439177e-01,
         7.50629185e-01, -1.37308116e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -1.89753490e+00,  3.22414704e+00,
         1.98322418e+00, -4.04615170e-02,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -7.26533324e-02, -4.79463445e-01,
        -4.81965811e-01, -4.91448664e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  8.76285082e-01,  4.46439177e-01,
        -4.81965811e-01,  3.58970475e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -8.02605959e-01, -4.79463445e-01,
        -4.81965811e-01, -4.88075897e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  2.19327718e-01,  4.46439177e-01,
         7.50629185e-01, -2.47645783e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -6.95759601e-03, -4.79463445e-01,
        -4.81965811e-01, -4.94098695e-01, -6.64833700e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  3.79917296e-01,  6.92775753e+00,
         1.98322418e+00,  6.97210836e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -2.04352542e+00, -4.79463445e-01,
         7.50629185e-01, -4.41579893e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-3.46145910e-01,  1.46024718e+00, -4.79463445e-01,
        -4.81965811e-01, -3.92674770e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -8.75601221e-01, -4.79463445e-01,
        -4.81965811e-01, -3.92674770e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  2.07340739e+00, -4.79463445e-01,
        -4.81965811e-01, -1.43571826e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  1.75222823e+00,  4.46439177e-01,
        -4.81965811e-01, -1.42126355e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  2.92322981e-01, -4.79463445e-01,
        -4.81965811e-01, -4.40857157e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-1.53181312e+00,  3.65318243e-01,  4.46439177e-01,
        -4.81965811e-01,  3.58970475e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-1.53181312e+00,  3.65318243e-01,  4.46439177e-01,
        -4.81965811e-01,  9.65586734e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-3.46145910e-01, -1.24057753e+00, -4.79463445e-01,
         7.50629185e-01, -2.67400562e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-1.53181312e+00,  1.16826613e+00, -4.79463445e-01,
        -4.81965811e-01,  8.83194851e-01, -1.91989383e+00,
         7.44590347e-01],
       [-1.53181312e+00,  5.11308769e-01,  4.46439177e-01,
        -4.81965811e-01,  3.80170726e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -4.37629646e-01, -4.79463445e-01,
        -4.81965811e-01, -4.40857157e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -7.26533324e-02, -4.79463445e-01,
        -4.81965811e-01, -4.93375959e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  3.41930253e-04, -4.79463445e-01,
        -4.81965811e-01, -4.60130112e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -8.75601221e-01, -4.79463445e-01,
        -4.81965811e-01, -4.93375959e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01,  1.53324245e+00, -4.79463445e-01,
        -4.81965811e-01, -4.88075897e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -2.33242910e-01, -4.79463445e-01,
        -4.81965811e-01, -5.03895138e-01, -1.91989383e+00,
         7.44590347e-01],
       [ 8.39521302e-01, -6.93113065e-01, -4.79463445e-01,
        -4.81965811e-01, -5.03494261e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  6.57299294e-01, -4.79463445e-01,
        -4.81965811e-01, -3.92674770e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  2.33619033e+00, -4.79463445e-01,
        -4.81965811e-01, -4.40857157e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  2.11720455e+00, -4.79463445e-01,
        -4.81965811e-01, -3.83038292e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.02535298e-01, -4.79463445e-01,
        -4.81965811e-01, -4.88075897e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -1.42571223e-02, -4.79463445e-01,
        -4.81965811e-01,  4.45617826e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.82830087e-01, -4.79463445e-01,
        -4.81965811e-01, -5.03976085e-01, -1.91989383e+00,
         7.44590347e-01],
       [ 8.39521302e-01, -1.02159175e+00,  3.22414704e+00,
         7.50629185e-01,  1.21672217e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  3.41930253e-04,  4.46439177e-01,
        -4.81965811e-01, -3.32928609e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.46332456e-01,  4.46439177e-01,
        -4.81965811e-01, -3.44492382e-01, -6.64833700e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -8.75601221e-01, -4.79463445e-01,
         7.50629185e-01, -4.63021055e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01,  1.29965761e+00, -4.79463445e-01,
        -4.81965811e-01, -4.93857783e-01, -6.64833700e-01,
         7.44590347e-01],
       [-1.53181312e+00,  7.30294557e-01, -4.79463445e-01,
        -4.81965811e-01,  2.31445267e+00,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -2.91639120e-01,  4.46439177e-01,
        -4.81965811e-01, -3.32928609e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -4.37629646e-01, -4.79463445e-01,
        -4.81965811e-01, -4.98756968e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  7.33371929e-02, -4.79463445e-01,
        -4.81965811e-01, -4.93375959e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  2.92322981e-01,  4.46439177e-01,
        -4.81965811e-01, -2.38491130e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -1.75154437e+00, -4.79463445e-01,
         7.50629185e-01, -4.02793071e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.09527087e+00,  4.46439177e-01,
         4.44841417e+00, -1.05507740e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-1.53181312e+00,  1.24126140e+00, -4.79463445e-01,
        -4.81965811e-01,  9.87855829e-02,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  2.16100170e+00, -4.79463445e-01,
        -4.81965811e-01, -1.42126355e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  4.38313506e-01, -4.79463445e-01,
        -4.81965811e-01,  1.30104135e-01, -1.91989383e+00,
         7.44590347e-01],
       [-3.46145910e-01, -5.83620171e-01,  4.46439177e-01,
         1.98322418e+00,  1.58130866e-01, -1.91989383e+00,
        -1.34302037e+00],
       [-3.46145910e-01, -1.60555385e+00,  4.46439177e-01,
         7.50629185e-01,  6.50579116e-02,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -5.83620171e-01,  4.46439177e-01,
        -4.81965811e-01, -5.03494261e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.09527087e+00, -4.79463445e-01,
         7.50629185e-01, -3.64648038e-01, -1.91989383e+00,
        -1.34302037e+00],
       [ 8.39521302e-01, -4.96025856e-01,  1.37234180e+00,
        -4.81965811e-01, -1.95126981e-01, -6.64833700e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -1.16758227e+00, -4.79463445e-01,
        -4.81965811e-01, -4.91849541e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01,  7.66792188e-01, -4.79463445e-01,
        -4.81965811e-01, -4.93857783e-01, -6.64833700e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -2.11652069e+00,  4.46439177e-01,
         1.98322418e+00, -2.46682135e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.02535298e-01, -4.79463445e-01,
        -4.81965811e-01, -4.88075897e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -4.34552273e-02, -4.79463445e-01,
        -4.81965811e-01, -4.91047786e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  1.46332456e-01,  4.46439177e-01,
        -4.81965811e-01, -1.42126355e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  2.99314770e+00, -4.79463445e-01,
        -4.81965811e-01,  2.46656526e-02, -1.91989383e+00,
         7.44590347e-01],
       [-1.53181312e+00,  3.41930253e-04, -4.79463445e-01,
        -4.81965811e-01,  4.53970725e-01, -1.91989383e+00,
        -1.34302037e+00],
       [ 8.39521302e-01,  1.46332456e-01, -4.79463445e-01,
        -4.81965811e-01,  4.45617826e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  1.22666234e+00, -4.79463445e-01,
        -4.81965811e-01,  3.20424565e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -2.33242910e-01, -4.79463445e-01,
        -4.81965811e-01, -5.03895138e-01, -1.91989383e+00,
         7.44590347e-01],
       [-1.53181312e+00,  2.26319507e+00, -4.79463445e-01,
        -4.81965811e-01, -2.03058606e-02,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -1.53255859e+00,  1.37234180e+00,
         1.98322418e+00,  1.92846435e-02,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -2.91639120e-01, -4.79463445e-01,
        -4.81965811e-01, -4.91047786e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -2.18643858e-01,  4.46439177e-01,
        -4.81965811e-01, -3.76132792e-01, -1.91989383e+00,
        -1.34302037e+00],
       [-3.46145910e-01, -1.97053016e+00,  4.46439177e-01,
         1.98322418e+00,  1.58130866e-01, -1.91989383e+00,
        -1.34302037e+00],
       [ 8.39521302e-01,  7.33371929e-02,  4.46439177e-01,
        -4.81965811e-01, -2.96309995e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -6.56615433e-01, -4.79463445e-01,
        -4.81965811e-01, -4.80688573e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  5.84304031e-01, -4.79463445e-01,
        -4.81965811e-01,  8.98613215e-01,  1.84528655e+00,
        -1.34302037e+00],
       [ 8.39521302e-01,  2.92322981e-01, -4.79463445e-01,
        -4.81965811e-01, -4.88075897e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  8.76285082e-01, -4.79463445e-01,
        -4.81965811e-01,  3.74185590e+00, -1.91989383e+00,
        -1.34302037e+00],
       [ 8.39521302e-01,  2.19327718e-01, -4.79463445e-01,
        -4.81965811e-01, -4.93375959e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  2.04420928e+00, -4.79463445e-01,
        -4.81965811e-01, -7.08164211e-02, -1.91989383e+00,
         7.44590347e-01],
       [-1.53181312e+00,  9.49280345e-01, -4.79463445e-01,
         7.50629185e-01,  3.42987494e+00,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -8.75601221e-01,  4.46439177e-01,
         7.50629185e-01, -2.53668582e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -1.45648595e-01, -4.79463445e-01,
        -4.81965811e-01, -3.92674770e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -6.56615433e-01, -4.79463445e-01,
        -4.81965811e-01, -4.90485016e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  7.30294557e-01, -4.79463445e-01,
        -4.81965811e-01, -4.91047786e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.02535298e-01, -4.79463445e-01,
        -4.81965811e-01, -4.88075897e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  6.57299294e-01, -4.79463445e-01,
        -4.81965811e-01, -1.77781321e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.46332456e-01, -4.79463445e-01,
        -4.81965811e-01, -4.82053098e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -4.37629646e-01, -4.79463445e-01,
         1.98322418e+00, -3.63765337e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-1.53181312e+00,  1.24126140e+00,  4.46439177e-01,
         7.50629185e-01,  3.69651547e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-3.46145910e-01, -8.02605959e-01,  4.46439177e-01,
        -4.81965811e-01, -1.42126355e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01,  5.84304031e-01,  4.46439177e-01,
         5.68100917e+00, -3.82933095e-02,  5.90226427e-01,
        -1.34302037e+00],
       [-3.46145910e-01,  2.92322981e-01, -4.79463445e-01,
        -4.81965811e-01, -3.92674770e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -8.75601221e-01, -4.79463445e-01,
         7.50629185e-01, -3.64648038e-01, -1.91989383e+00,
        -1.34302037e+00],
       [ 8.39521302e-01, -9.04799326e-01, -4.79463445e-01,
        -4.81965811e-01, -4.93857783e-01, -6.64833700e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -4.74127277e-01, -4.79463445e-01,
        -4.81965811e-01, -5.03895138e-01, -1.91989383e+00,
         7.44590347e-01],
       [ 8.39521302e-01,  2.19327718e-01,  2.29824442e+00,
        -4.81965811e-01, -3.37746848e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-3.46145910e-01,  1.60623771e+00, -4.79463445e-01,
        -4.81965811e-01, -3.92674770e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.29965761e+00, -4.79463445e-01,
        -4.81965811e-01, -4.92331365e-01, -6.64833700e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -1.89753490e+00,  4.46439177e-01,
         7.50629185e-01, -3.21364836e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-1.53181312e+00,  8.76285082e-01, -4.79463445e-01,
        -4.81965811e-01, -1.36585380e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -5.69021118e-01, -4.79463445e-01,
        -4.81965811e-01, -3.64569019e-01, -1.91989383e+00,
         7.44590347e-01],
       [ 8.39521302e-01, -7.36910222e-01,  4.46439177e-01,
        -4.81965811e-01, -3.64569019e-01, -1.91989383e+00,
        -1.34302037e+00],
       [ 8.39521302e-01, -1.45648595e-01,  1.37234180e+00,
        -4.81965811e-01, -4.90485016e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -8.75601221e-01, -4.79463445e-01,
        -4.81965811e-01, -4.21584202e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -5.83620171e-01, -4.79463445e-01,
        -4.81965811e-01, -4.93857783e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -7.29610696e-01, -4.79463445e-01,
        -4.81965811e-01, -4.90485016e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  3.65318243e-01,  4.46439177e-01,
         7.50629185e-01, -2.52945846e-01,  5.90226427e-01,
        -1.34302037e+00],
       [-1.53181312e+00, -1.45648595e-01,  4.46439177e-01,
        -4.81965811e-01,  9.40450946e-01, -1.91989383e+00,
         7.44590347e-01],
       [ 8.39521302e-01, -6.56615433e-01, -4.79463445e-01,
        -4.81965811e-01, -4.88075897e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -9.04799326e-01, -4.79463445e-01,
        -4.81965811e-01, -4.93857783e-01, -6.64833700e-01,
        -1.34302037e+00],
       [-3.46145910e-01,  3.41930253e-04, -4.79463445e-01,
        -4.81965811e-01, -4.40857157e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -6.42016381e-01,  2.29824442e+00,
         7.50629185e-01, -1.52404621e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -1.09458701e+00, -4.79463445e-01,
        -4.81965811e-01, -5.03976085e-01, -1.91989383e+00,
        -1.34302037e+00],
       [-3.46145910e-01, -9.48596484e-01, -4.79463445e-01,
        -4.81965811e-01, -4.11947725e-01, -1.91989383e+00,
        -1.34302037e+00],
       [-3.46145910e-01,  1.46024718e+00, -4.79463445e-01,
        -4.81965811e-01, -4.40857157e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01,  3.41930253e-04, -4.79463445e-01,
        -4.81965811e-01, -4.88075897e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -2.18643858e-01,  4.46439177e-01,
        -4.81965811e-01, -2.38491130e-01,  5.90226427e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -9.48596484e-01, -4.79463445e-01,
        -4.81965811e-01, -4.76271212e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  3.41930253e-04, -4.79463445e-01,
        -4.81965811e-01, -4.57615796e-02, -1.91989383e+00,
        -1.34302037e+00],
       [-1.53181312e+00,  5.84304031e-01, -4.79463445e-01,
         7.50629185e-01,  2.31445267e+00,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -4.34552273e-02, -4.79463445e-01,
        -4.81965811e-01, -4.91047786e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -1.45648595e-01, -4.79463445e-01,
        -4.81965811e-01, -4.40857157e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01, -9.48596484e-01,  4.46439177e-01,
        -4.81965811e-01, -5.07267905e-01,  5.90226427e-01,
         7.44590347e-01],
       [-1.53181312e+00,  6.57299294e-01, -4.79463445e-01,
        -4.81965811e-01, -6.43223185e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01, -7.26533324e-02,  4.46439177e-01,
        -4.81965811e-01, -2.38491130e-01,  5.90226427e-01,
         7.44590347e-01],
       [ 8.39521302e-01,  1.02535298e-01,  4.46439177e-01,
        -4.81965811e-01, -1.77781321e-01, -6.64833700e-01,
        -1.34302037e+00],
       [ 8.39521302e-01, -8.02605959e-01, -4.79463445e-01,
        -4.81965811e-01, -4.91047786e-01,  5.90226427e-01,
         7.44590347e-01],
       [-3.46145910e-01,  1.46332456e-01, -4.79463445e-01,
        -4.81965811e-01, -3.92674770e-01,  5.90226427e-01,
        -1.34302037e+00]])

In [16]:
import tensorflow as tf
import keras
tf.__version__

'2.6.0'

In [17]:
### Initializing the ANN
ann = tf.keras.models.Sequential()
### Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=14, activation='relu'))
ann.add(tf.keras.layers.Dense(units=7, activation='selu'))
ann.add(tf.keras.layers.Dense(units=14, activation='relu'))
ann.add(tf.keras.layers.Dense(units=70, activation='relu'))
ann.add(tf.keras.layers.Dense(units=14, activation='relu'))
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
### Compiling the ANN
ann.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])
### Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 10, epochs = 200)

Epoch 1/200
76/76 [==============================] - 1s 771us/step - loss: 0.6717 - accuracy: 0.6433
Epoch 2/200
76/76 [==============================] - 0s 798us/step - loss: 0.6464 - accuracy: 0.6552
Epoch 3/200
76/76 [==============================] - 0s 864us/step - loss: 0.6195 - accuracy: 0.6565
Epoch 4/200
76/76 [==============================] - 0s 824us/step - loss: 0.5870 - accuracy: 0.7133
Epoch 5/200
76/76 [==============================] - 0s 811us/step - loss: 0.5516 - accuracy: 0.7490
Epoch 6/200
76/76 [==============================] - 0s 864us/step - loss: 0.5218 - accuracy: 0.7688
Epoch 7/200
76/76 [==============================] - 0s 864us/step - loss: 0.4997 - accuracy: 0.7794
Epoch 8/200
76/76 [==============================] - 0s 838us/step - loss: 0.4840 - accuracy: 0.7807
Epoch 9/200
76/76 [==============================] - 0s 864us/step - loss: 0.4714 - accuracy: 0.7807
Epoch 10/200
76/76 [==============================] - 0s 864us/step - loss: 0.4608 - accuracy: 0.79260s - loss: 0.4625 - accuracy: 0.79
Epoch 11/200
76/76 [==============================] - 0s 851us/step - loss: 0.4517 - accuracy: 0.7952
Epoch 12/200
76/76 [==============================] - 0s 851us/step - loss: 0.4457 - accuracy: 0.7979
Epoch 13/200
76/76 [==============================] - 0s 838us/step - loss: 0.4397 - accuracy: 0.8058
Epoch 14/200
76/76 [==============================] - 0s 838us/step - loss: 0.4345 - accuracy: 0.8032
Epoch 15/200
76/76 [==============================] - 0s 824us/step - loss: 0.4301 - accuracy: 0.8058
Epoch 16/200
76/76 [==============================] - 0s 838us/step - loss: 0.4255 - accuracy: 0.8137
Epoch 17/200
76/76 [==============================] - 0s 869us/step - loss: 0.4242 - accuracy: 0.8071
Epoch 18/200
76/76 [==============================] - 0s 824us/step - loss: 0.4206 - accuracy: 0.8137
Epoch 19/200
76/76 [==============================] - 0s 851us/step - loss: 0.4170 - accuracy: 0.8137
Epoch 20/200
76/76 [==============================] - 0s 851us/step - loss: 0.4144 - accuracy: 0.8124
Epoch 21/200
76/76 [==============================] - 0s 851us/step - loss: 0.4103 - accuracy: 0.8164
Epoch 22/200
76/76 [==============================] - 0s 891us/step - loss: 0.4105 - accuracy: 0.8058
Epoch 23/200
76/76 [==============================] - 0s 837us/step - loss: 0.4072 - accuracy: 0.8177
Epoch 24/200
76/76 [==============================] - 0s 864us/step - loss: 0.4041 - accuracy: 0.8177
Epoch 25/200
76/76 [==============================] - 0s 864us/step - loss: 0.4012 - accuracy: 0.8230
Epoch 26/200
76/76 [==============================] - 0s 851us/step - loss: 0.3996 - accuracy: 0.8190
Epoch 27/200
76/76 [==============================] - 0s 798us/step - loss: 0.3962 - accuracy: 0.8269
Epoch 28/200
76/76 [==============================] - 0s 838us/step - loss: 0.3947 - accuracy: 0.8217
Epoch 29/200
76/76 [==============================] - 0s 878us/step - loss: 0.3929 - accuracy: 0.8269
Epoch 30/200
76/76 [==============================] - 0s 918us/step - loss: 0.3895 - accuracy: 0.82830s - loss: 0.4012 - accuracy: 0.81
Epoch 31/200
76/76 [==============================] - 0s 904us/step - loss: 0.3886 - accuracy: 0.8230
Epoch 32/200
76/76 [==============================] - 0s 878us/step - loss: 0.3865 - accuracy: 0.8230
Epoch 33/200
76/76 [==============================] - 0s 878us/step - loss: 0.3854 - accuracy: 0.8349
Epoch 34/200
76/76 [==============================] - 0s 851us/step - loss: 0.3853 - accuracy: 0.8336
Epoch 35/200
76/76 [==============================] - 0s 865us/step - loss: 0.3810 - accuracy: 0.8428
Epoch 36/200
76/76 [==============================] - 0s 864us/step - loss: 0.3769 - accuracy: 0.8415
Epoch 37/200
76/76 [==============================] - 0s 891us/step - loss: 0.3815 - accuracy: 0.8283
Epoch 38/200
76/76 [==============================] - 0s 851us/step - loss: 0.3783 - accuracy: 0.8362
Epoch 39/200
76/76 [==============================] - 0s 851us/step - loss: 0.3732 - accuracy: 0.8388
Epoch 40/200
76/76 [==============================] - 0s 824us/step - loss: 0.3771 - accuracy: 0.8415
Epoch 41/200
76/76 [==============================] - 0s 871us/step - loss: 0.3748 - accuracy: 0.8349
Epoch 42/200
76/76 [==============================] - 0s 891us/step - loss: 0.3714 - accuracy: 0.8441
Epoch 43/200
76/76 [==============================] - 0s 838us/step - loss: 0.3708 - accuracy: 0.8468
Epoch 44/200
76/76 [==============================] - 0s 904us/step - loss: 0.3728 - accuracy: 0.8362
Epoch 45/200
76/76 [==============================] - 0s 878us/step - loss: 0.3716 - accuracy: 0.8388
Epoch 46/200
76/76 [==============================] - 0s 878us/step - loss: 0.3684 - accuracy: 0.8402
Epoch 47/200
76/76 [==============================] - 0s 864us/step - loss: 0.3683 - accuracy: 0.8402
Epoch 48/200
76/76 [==============================] - 0s 971us/step - loss: 0.3696 - accuracy: 0.8349
Epoch 49/200
76/76 [==============================] - 0s 931us/step - loss: 0.3622 - accuracy: 0.8468
Epoch 50/200
76/76 [==============================] - 0s 971us/step - loss: 0.3673 - accuracy: 0.8415
Epoch 51/200
76/76 [==============================] - 0s 944us/step - loss: 0.3660 - accuracy: 0.8441
Epoch 52/200
76/76 [==============================] - 0s 944us/step - loss: 0.3672 - accuracy: 0.8481
Epoch 53/200
76/76 [==============================] - 0s 918us/step - loss: 0.3640 - accuracy: 0.8507
Epoch 54/200
76/76 [==============================] - 0s 931us/step - loss: 0.3605 - accuracy: 0.8534
Epoch 55/200
76/76 [==============================] - 0s 811us/step - loss: 0.3603 - accuracy: 0.8494
Epoch 56/200
76/76 [==============================] - 0s 851us/step - loss: 0.3586 - accuracy: 0.8573
Epoch 57/200
76/76 [==============================] - 0s 798us/step - loss: 0.3609 - accuracy: 0.8481
Epoch 58/200
76/76 [==============================] - 0s 811us/step - loss: 0.3569 - accuracy: 0.85470s - loss: 0.3637 - accuracy: 0.85
Epoch 59/200
76/76 [==============================] - 0s 851us/step - loss: 0.3604 - accuracy: 0.85340s - loss: 0.3532 - accuracy: 0.85
Epoch 60/200
76/76 [==============================] - 0s 851us/step - loss: 0.3569 - accuracy: 0.8534
Epoch 61/200
76/76 [==============================] - 0s 811us/step - loss: 0.3550 - accuracy: 0.8573
Epoch 62/200
76/76 [==============================] - 0s 852us/step - loss: 0.3565 - accuracy: 0.8468
Epoch 63/200
76/76 [==============================] - 0s 838us/step - loss: 0.3529 - accuracy: 0.86260s - loss: 0.3475 - accuracy: 0.86
Epoch 64/200
76/76 [==============================] - 0s 851us/step - loss: 0.3517 - accuracy: 0.8573
Epoch 65/200
76/76 [==============================] - 0s 838us/step - loss: 0.3552 - accuracy: 0.8507
Epoch 66/200
76/76 [==============================] - 0s 891us/step - loss: 0.3519 - accuracy: 0.8573
Epoch 67/200
76/76 [==============================] - 0s 931us/step - loss: 0.3507 - accuracy: 0.8573
Epoch 68/200
76/76 [==============================] - 0s 918us/step - loss: 0.3500 - accuracy: 0.8600
Epoch 69/200
76/76 [==============================] - 0s 931us/step - loss: 0.3461 - accuracy: 0.8507
Epoch 70/200
76/76 [==============================] - 0s 851us/step - loss: 0.3480 - accuracy: 0.8494
Epoch 71/200
76/76 [==============================] - 0s 824us/step - loss: 0.3476 - accuracy: 0.8560
Epoch 72/200
76/76 [==============================] - 0s 851us/step - loss: 0.3470 - accuracy: 0.8587
Epoch 73/200
76/76 [==============================] - 0s 864us/step - loss: 0.3472 - accuracy: 0.8626
Epoch 74/200
76/76 [==============================] - 0s 878us/step - loss: 0.3499 - accuracy: 0.8626
Epoch 75/200
76/76 [==============================] - 0s 838us/step - loss: 0.3509 - accuracy: 0.8613
Epoch 76/200
76/76 [==============================] - 0s 878us/step - loss: 0.3434 - accuracy: 0.8560
Epoch 77/200
76/76 [==============================] - 0s 838us/step - loss: 0.3436 - accuracy: 0.8679
Epoch 78/200
76/76 [==============================] - 0s 878us/step - loss: 0.3393 - accuracy: 0.8692
Epoch 79/200

76/76 [==============================] - 0s 846us/step - loss: 0.3456 - accuracy: 0.8653
Epoch 80/200
76/76 [==============================] - 0s 851us/step - loss: 0.3435 - accuracy: 0.8573
Epoch 81/200
76/76 [==============================] - 0s 811us/step - loss: 0.3417 - accuracy: 0.8639
Epoch 82/200
76/76 [==============================] - 0s 838us/step - loss: 0.3413 - accuracy: 0.8613
Epoch 83/200
76/76 [==============================] - 0s 811us/step - loss: 0.3370 - accuracy: 0.8719
Epoch 84/200
76/76 [==============================] - 0s 798us/step - loss: 0.3401 - accuracy: 0.85470s - loss: 0.3412 - accuracy: 0.85
Epoch 85/200
76/76 [==============================] - 0s 811us/step - loss: 0.3422 - accuracy: 0.8587
Epoch 86/200
76/76 [==============================] - 0s 851us/step - loss: 0.3421 - accuracy: 0.8639
Epoch 87/200
76/76 [==============================] - 0s 878us/step - loss: 0.3409 - accuracy: 0.8560
Epoch 88/200
76/76 [==============================] - 0s 891us/step - loss: 0.3394 - accuracy: 0.8573
Epoch 89/200
76/76 [==============================] - 0s 837us/step - loss: 0.3439 - accuracy: 0.8587
Epoch 90/200
76/76 [==============================] - 0s 805us/step - loss: 0.3397 - accuracy: 0.8560
Epoch 91/200
76/76 [==============================] - 0s 838us/step - loss: 0.3374 - accuracy: 0.85870s - loss: 0.3132 - accuracy: 0.86
Epoch 92/200
76/76 [==============================] - 0s 971us/step - loss: 0.3414 - accuracy: 0.8573
Epoch 93/200
76/76 [==============================] - 0s 998us/step - loss: 0.3378 - accuracy: 0.8534
Epoch 94/200
76/76 [==============================] - 0s 984us/step - loss: 0.3403 - accuracy: 0.8481
Epoch 95/200
76/76 [==============================] - 0s 851us/step - loss: 0.3387 - accuracy: 0.8560
Epoch 96/200
76/76 [==============================] - 0s 824us/step - loss: 0.3430 - accuracy: 0.8520
Epoch 97/200
76/76 [==============================] - 0s 811us/step - loss: 0.3375 - accuracy: 0.8626
Epoch 98/200
76/76 [==============================] - 0s 811us/step - loss: 0.3346 - accuracy: 0.8639
Epoch 99/200
76/76 [==============================] - 0s 824us/step - loss: 0.3348 - accuracy: 0.8666
Epoch 100/200
76/76 [==============================] - 0s 818us/step - loss: 0.3359 - accuracy: 0.8547
Epoch 101/200
76/76 [==============================] - 0s 838us/step - loss: 0.3338 - accuracy: 0.8626
Epoch 102/200
76/76 [==============================] - 0s 824us/step - loss: 0.3378 - accuracy: 0.8534
Epoch 103/200
76/76 [==============================] - 0s 824us/step - loss: 0.3349 - accuracy: 0.8626
Epoch 104/200
76/76 [==============================] - 0s 997us/step - loss: 0.3345 - accuracy: 0.8653
Epoch 105/200
76/76 [==============================] - 0s 971us/step - loss: 0.3333 - accuracy: 0.8613
Epoch 106/200
76/76 [==============================] - 0s 931us/step - loss: 0.3321 - accuracy: 0.8587
Epoch 107/200
76/76 [==============================] - 0s 811us/step - loss: 0.3345 - accuracy: 0.8639
Epoch 108/200
76/76 [==============================] - 0s 785us/step - loss: 0.3330 - accuracy: 0.8587
Epoch 109/200
76/76 [==============================] - 0s 811us/step - loss: 0.3358 - accuracy: 0.8639
Epoch 110/200
76/76 [==============================] - 0s 838us/step - loss: 0.3325 - accuracy: 0.86130s - loss: 0.3248 - accuracy: 0.86
Epoch 111/200
76/76 [==============================] - 0s 837us/step - loss: 0.3332 - accuracy: 0.86130s - loss: 0.3254 - accuracy: 0.86
Epoch 112/200
76/76 [==============================] - 0s 824us/step - loss: 0.3334 - accuracy: 0.8679
Epoch 113/200
76/76 [==============================] - 0s 837us/step - loss: 0.3304 - accuracy: 0.8679
Epoch 114/200
76/76 [==============================] - 0s 837us/step - loss: 0.3335 - accuracy: 0.8666
Epoch 115/200
76/76 [==============================] - 0s 811us/step - loss: 0.3307 - accuracy: 0.8653
Epoch 116/200
76/76 [==============================] - 0s 811us/step - loss: 0.3332 - accuracy: 0.8653
Epoch 117/200
76/76 [==============================] - 0s 838us/step - loss: 0.3245 - accuracy: 0.87320s - loss: 0.3262 - accuracy: 0.86
Epoch 118/200
76/76 [==============================] - 0s 838us/step - loss: 0.3366 - accuracy: 0.8639
Epoch 119/200
76/76 [==============================] - 0s 931us/step - loss: 0.3290 - accuracy: 0.85470s - loss: 0.3158 - accuracy: 0.85
Epoch 120/200
76/76 [==============================] - 0s 824us/step - loss: 0.3290 - accuracy: 0.8600
Epoch 121/200
76/76 [==============================] - 0s 838us/step - loss: 0.3311 - accuracy: 0.8560
Epoch 122/200
76/76 [==============================] - 0s 817us/step - loss: 0.3320 - accuracy: 0.8653
Epoch 123/200
76/76 [==============================] - 0s 771us/step - loss: 0.3265 - accuracy: 0.8587
Epoch 124/200
76/76 [==============================] - 0s 758us/step - loss: 0.3325 - accuracy: 0.8587
Epoch 125/200
76/76 [==============================] - 0s 798us/step - loss: 0.3328 - accuracy: 0.8653
Epoch 126/200
76/76 [==============================] - 0s 771us/step - loss: 0.3275 - accuracy: 0.8547
Epoch 127/200
76/76 [==============================] - 0s 785us/step - loss: 0.3253 - accuracy: 0.8626
Epoch 128/200
76/76 [==============================] - 0s 785us/step - loss: 0.3224 - accuracy: 0.8626
Epoch 129/200
76/76 [==============================] - 0s 785us/step - loss: 0.3259 - accuracy: 0.86390s - loss: 0.3235 - accuracy: 0.86
Epoch 130/200
76/76 [==============================] - 0s 758us/step - loss: 0.3241 - accuracy: 0.8613
Epoch 131/200
76/76 [==============================] - 0s 771us/step - loss: 0.3297 - accuracy: 0.8639
Epoch 132/200
76/76 [==============================] - 0s 745us/step - loss: 0.3273 - accuracy: 0.8639
Epoch 133/200
76/76 [==============================] - 0s 798us/step - loss: 0.3264 - accuracy: 0.8679
Epoch 134/200
76/76 [==============================] - 0s 745us/step - loss: 0.3222 - accuracy: 0.8653
Epoch 135/200
76/76 [==============================] - 0s 771us/step - loss: 0.3217 - accuracy: 0.8600
Epoch 136/200
76/76 [==============================] - 0s 771us/step - loss: 0.3244 - accuracy: 0.8653
Epoch 137/200
76/76 [==============================] - 0s 771us/step - loss: 0.3264 - accuracy: 0.8600
Epoch 138/200
76/76 [==============================] - 0s 758us/step - loss: 0.3256 - accuracy: 0.8613
Epoch 139/200
76/76 [==============================] - 0s 785us/step - loss: 0.3215 - accuracy: 0.8679
Epoch 140/200
76/76 [==============================] - 0s 798us/step - loss: 0.3242 - accuracy: 0.8639
Epoch 141/200
76/76 [==============================] - 0s 798us/step - loss: 0.3253 - accuracy: 0.8679
Epoch 142/200
76/76 [==============================] - 0s 776us/step - loss: 0.3293 - accuracy: 0.8639
Epoch 143/200
76/76 [==============================] - 0s 745us/step - loss: 0.3201 - accuracy: 0.8653
Epoch 144/200
76/76 [==============================] - 0s 785us/step - loss: 0.3205 - accuracy: 0.8666
Epoch 145/200
76/76 [==============================] - 0s 758us/step - loss: 0.3233 - accuracy: 0.8679
Epoch 146/200
76/76 [==============================] - 0s 785us/step - loss: 0.3215 - accuracy: 0.8692
Epoch 147/200
76/76 [==============================] - 0s 771us/step - loss: 0.3199 - accuracy: 0.8626
Epoch 148/200
76/76 [==============================] - 0s 758us/step - loss: 0.3157 - accuracy: 0.8692
Epoch 149/200
76/76 [==============================] - 0s 785us/step - loss: 0.3207 - accuracy: 0.8666
Epoch 150/200
76/76 [==============================] - 0s 745us/step - loss: 0.3217 - accuracy: 0.8719
Epoch 151/200
76/76 [==============================] - 0s 798us/step - loss: 0.3182 - accuracy: 0.8560
Epoch 152/200
76/76 [==============================] - 0s 758us/step - loss: 0.3184 - accuracy: 0.8666
Epoch 153/200
76/76 [==============================] - 0s 771us/step - loss: 0.3209 - accuracy: 0.8639
Epoch 154/200
76/76 [==============================] - 0s 771us/step - loss: 0.3179 - accuracy: 0.8653
Epoch 155/200
76/76 [==============================] - 0s 745us/step - loss: 0.3225 - accuracy: 0.8745
Epoch 156/200

76/76 [==============================] - 0s 769us/step - loss: 0.3172 - accuracy: 0.8692
Epoch 157/200
76/76 [==============================] - 0s 785us/step - loss: 0.3178 - accuracy: 0.8705
Epoch 158/200
76/76 [==============================] - 0s 771us/step - loss: 0.3204 - accuracy: 0.8692
Epoch 159/200
76/76 [==============================] - 0s 798us/step - loss: 0.3203 - accuracy: 0.8719
Epoch 160/200
76/76 [==============================] - 0s 757us/step - loss: 0.3102 - accuracy: 0.8626
Epoch 161/200
76/76 [==============================] - 0s 731us/step - loss: 0.3222 - accuracy: 0.8639
Epoch 162/200
76/76 [==============================] - 0s 771us/step - loss: 0.3134 - accuracy: 0.8692
Epoch 163/200
76/76 [==============================] - 0s 771us/step - loss: 0.3103 - accuracy: 0.8771
Epoch 164/200
76/76 [==============================] - 0s 785us/step - loss: 0.3168 - accuracy: 0.8639
Epoch 165/200
76/76 [==============================] - 0s 785us/step - loss: 0.3189 - accuracy: 0.8613
Epoch 166/200
76/76 [==============================] - 0s 758us/step - loss: 0.3130 - accuracy: 0.8705
Epoch 167/200
76/76 [==============================] - 0s 772us/step - loss: 0.3157 - accuracy: 0.8679
Epoch 168/200
76/76 [==============================] - 0s 785us/step - loss: 0.3241 - accuracy: 0.8587
Epoch 169/200
76/76 [==============================] - 0s 785us/step - loss: 0.3153 - accuracy: 0.87450s - loss: 0.3082 - accuracy: 0.87
Epoch 170/200
76/76 [==============================] - 0s 785us/step - loss: 0.3145 - accuracy: 0.8679
Epoch 171/200
76/76 [==============================] - 0s 758us/step - loss: 0.3147 - accuracy: 0.8705
Epoch 172/200
76/76 [==============================] - 0s 785us/step - loss: 0.3103 - accuracy: 0.8653
Epoch 173/200
76/76 [==============================] - 0s 771us/step - loss: 0.3173 - accuracy: 0.8653
Epoch 174/200
76/76 [==============================] - 0s 771us/step - loss: 0.3149 - accuracy: 0.8705
Epoch 175/200
76/76 [==============================] - 0s 785us/step - loss: 0.3103 - accuracy: 0.8705
Epoch 176/200
76/76 [==============================] - 0s 758us/step - loss: 0.3178 - accuracy: 0.8692
Epoch 177/200
76/76 [==============================] - 0s 785us/step - loss: 0.3143 - accuracy: 0.8732
Epoch 178/200
76/76 [==============================] - 0s 785us/step - loss: 0.3151 - accuracy: 0.8692
Epoch 179/200
76/76 [==============================] - 0s 771us/step - loss: 0.3095 - accuracy: 0.8587
Epoch 180/200
76/76 [==============================] - 0s 771us/step - loss: 0.3092 - accuracy: 0.8732
Epoch 181/200
76/76 [==============================] - 0s 798us/step - loss: 0.3072 - accuracy: 0.8732
Epoch 182/200
76/76 [==============================] - 0s 745us/step - loss: 0.3078 - accuracy: 0.8719
Epoch 183/200
76/76 [==============================] - 0s 798us/step - loss: 0.3121 - accuracy: 0.8732
Epoch 184/200
76/76 [==============================] - 0s 798us/step - loss: 0.3048 - accuracy: 0.8745
Epoch 185/200
76/76 [==============================] - 0s 772us/step - loss: 0.3172 - accuracy: 0.8639
Epoch 186/200
76/76 [==============================] - 0s 769us/step - loss: 0.3061 - accuracy: 0.8745
Epoch 187/200
76/76 [==============================] - 0s 745us/step - loss: 0.3030 - accuracy: 0.8705
Epoch 188/200
76/76 [==============================] - 0s 1ms/step - loss: 0.3089 - accuracy: 0.8705
Epoch 189/200
76/76 [==============================] - 0s 785us/step - loss: 0.3119 - accuracy: 0.86790s - loss: 0.3145 - accuracy: 0.86
Epoch 190/200
76/76 [==============================] - 0s 758us/step - loss: 0.3070 - accuracy: 0.8666
Epoch 191/200
76/76 [==============================] - 0s 785us/step - loss: 0.3082 - accuracy: 0.8705
Epoch 192/200
76/76 [==============================] - 0s 785us/step - loss: 0.3071 - accuracy: 0.8679
Epoch 193/200
76/76 [==============================] - 0s 758us/step - loss: 0.2979 - accuracy: 0.8824
Epoch 194/200
76/76 [==============================] - 0s 798us/step - loss: 0.3130 - accuracy: 0.8692
Epoch 195/200
76/76 [==============================] - 0s 758us/step - loss: 0.3072 - accuracy: 0.8798
Epoch 196/200
76/76 [==============================] - 0s 745us/step - loss: 0.3068 - accuracy: 0.8705
Epoch 197/200
76/76 [==============================] - 0s 771us/step - loss: 0.3147 - accuracy: 0.8653
Epoch 198/200
76/76 [==============================] - 0s 785us/step - loss: 0.3071 - accuracy: 0.8798
Epoch 199/200
76/76 [==============================] - 0s 771us/step - loss: 0.3072 - accuracy: 0.8719
Epoch 200/200
76/76 [==============================] - 0s 758us/step - loss: 0.3032 - accuracy: 0.8732

In [18]:
from sklearn.metrics import average_precision_score
y_pred_train = np.round(ann.predict(X_train),0)
y_pred_test = np.round(ann.predict(X_test),0)
precision_test = average_precision_score(y_test, y_pred_test)
precision_train = average_precision_score(y_train, y_pred_train)
print(precision_train)
print(precision_test)

0.7841789460076128
0.5873213668990881

In [19]:
from sklearn.metrics import f1_score
f1_train = f1_score(y_train, y_pred_train, average='macro')
f1_test = f1_score(y_test, y_pred_test, average='macro')
print(f1_train)
print(f1_test)

0.850615229840582
0.7861702127659574

In [20]:
### Initializing the ANN
ann_p = tf.keras.models.Sequential()
### Adding the input layer and the first hidden layer
ann_p.add(tf.keras.layers.Dense(units=16, activation='elu'))
### Adding the second hidden layer
ann_p.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
### Compiling the ANN
ann_p.compile(optimizer = 'RMSprop', loss = 'poisson', metrics = ['accuracy'])
### Training the ANN on the Training set
ann_p.fit(X_train, y_train, batch_size = 8, epochs = 250)

Epoch 1/250
95/95 [==============================] - 0s 626us/step - loss: 0.7236 - accuracy: 0.6671
Epoch 2/250
95/95 [==============================] - 0s 657us/step - loss: 0.6779 - accuracy: 0.7569
Epoch 3/250
95/95 [==============================] - 0s 636us/step - loss: 0.6583 - accuracy: 0.7820
Epoch 4/250
95/95 [==============================] - 0s 605us/step - loss: 0.6490 - accuracy: 0.7939
Epoch 5/250
95/95 [==============================] - ETA: 0s - loss: 0.6578 - accuracy: 0.79 - 0s 636us/step - loss: 0.6441 - accuracy: 0.8018
Epoch 6/250
95/95 [==============================] - 0s 594us/step - loss: 0.6410 - accuracy: 0.8071
Epoch 7/250
95/95 [==============================] - 0s 637us/step - loss: 0.6398 - accuracy: 0.8071
Epoch 8/250
95/95 [==============================] - 0s 605us/step - loss: 0.6385 - accuracy: 0.8111
Epoch 9/250
95/95 [==============================] - 0s 594us/step - loss: 0.6376 - accuracy: 0.8098
Epoch 10/250
95/95 [==============================] - 0s 594us/step - loss: 0.6373 - accuracy: 0.8098
Epoch 11/250
95/95 [==============================] - 0s 690us/step - loss: 0.6364 - accuracy: 0.8098
Epoch 12/250
95/95 [==============================] - 0s 615us/step - loss: 0.6363 - accuracy: 0.8124
Epoch 13/250
95/95 [==============================] - 0s 615us/step - loss: 0.6360 - accuracy: 0.8124
Epoch 14/250
95/95 [==============================] - 0s 583us/step - loss: 0.6356 - accuracy: 0.8164
Epoch 15/250
95/95 [==============================] - 0s 647us/step - loss: 0.6352 - accuracy: 0.81240s - loss: 0.6379 - accuracy: 0.80
Epoch 16/250
95/95 [==============================] - 0s 615us/step - loss: 0.6350 - accuracy: 0.8098
Epoch 17/250
95/95 [==============================] - 0s 584us/step - loss: 0.6347 - accuracy: 0.8137
Epoch 18/250
95/95 [==============================] - 0s 658us/step - loss: 0.6347 - accuracy: 0.8111
Epoch 19/250
95/95 [==============================] - 0s 573us/step - loss: 0.6343 - accuracy: 0.8124
Epoch 20/250
95/95 [==============================] - 0s 626us/step - loss: 0.6340 - accuracy: 0.8124
Epoch 21/250
95/95 [==============================] - 0s 604us/step - loss: 0.6338 - accuracy: 0.8137
Epoch 22/250
95/95 [==============================] - 0s 626us/step - loss: 0.6340 - accuracy: 0.8137
Epoch 23/250
95/95 [==============================] - 0s 637us/step - loss: 0.6335 - accuracy: 0.8151
Epoch 24/250
95/95 [==============================] - 0s 594us/step - loss: 0.6335 - accuracy: 0.8137
Epoch 25/250
95/95 [==============================] - ETA: 0s - loss: 0.6380 - accuracy: 0.80 - 0s 626us/step - loss: 0.6332 - accuracy: 0.8111
Epoch 26/250
95/95 [==============================] - 0s 562us/step - loss: 0.6330 - accuracy: 0.8203
Epoch 27/250
95/95 [==============================] - 0s 658us/step - loss: 0.6330 - accuracy: 0.8151
Epoch 28/250
95/95 [==============================] - 0s 615us/step - loss: 0.6325 - accuracy: 0.8164
Epoch 29/250
95/95 [==============================] - 0s 594us/step - loss: 0.6325 - accuracy: 0.8124
Epoch 30/250
95/95 [==============================] - 0s 626us/step - loss: 0.6322 - accuracy: 0.8151
Epoch 31/250
95/95 [==============================] - 0s 594us/step - loss: 0.6322 - accuracy: 0.8151
Epoch 32/250
95/95 [==============================] - 0s 668us/step - loss: 0.6318 - accuracy: 0.8190
Epoch 33/250
95/95 [==============================] - 0s 615us/step - loss: 0.6318 - accuracy: 0.8137
Epoch 34/250
95/95 [==============================] - 0s 552us/step - loss: 0.6318 - accuracy: 0.8177
Epoch 35/250
95/95 [==============================] - 0s 679us/step - loss: 0.6313 - accuracy: 0.8190
Epoch 36/250
95/95 [==============================] - 0s 573us/step - loss: 0.6313 - accuracy: 0.8164
Epoch 37/250
95/95 [==============================] - 0s 604us/step - loss: 0.6310 - accuracy: 0.8190
Epoch 38/250
95/95 [==============================] - 0s 594us/step - loss: 0.6309 - accuracy: 0.8203
Epoch 39/250
95/95 [==============================] - 0s 626us/step - loss: 0.6308 - accuracy: 0.8190
Epoch 40/250
95/95 [==============================] - 0s 594us/step - loss: 0.6306 - accuracy: 0.8190
Epoch 41/250
95/95 [==============================] - 0s 615us/step - loss: 0.6301 - accuracy: 0.8190
Epoch 42/250
95/95 [==============================] - 0s 689us/step - loss: 0.6302 - accuracy: 0.8164
Epoch 43/250
95/95 [==============================] - ETA: 0s - loss: 0.6354 - accuracy: 0.82 - 0s 700us/step - loss: 0.6301 - accuracy: 0.8124
Epoch 44/250
95/95 [==============================] - 0s 668us/step - loss: 0.6299 - accuracy: 0.8217
Epoch 45/250
95/95 [==============================] - 0s 668us/step - loss: 0.6298 - accuracy: 0.8190
Epoch 46/250
95/95 [==============================] - 0s 668us/step - loss: 0.6295 - accuracy: 0.8203
Epoch 47/250
95/95 [==============================] - 0s 690us/step - loss: 0.6295 - accuracy: 0.8164
Epoch 48/250
95/95 [==============================] - 0s 700us/step - loss: 0.6295 - accuracy: 0.8177
Epoch 49/250
95/95 [==============================] - 0s 700us/step - loss: 0.6293 - accuracy: 0.8177
Epoch 50/250
95/95 [==============================] - 0s 679us/step - loss: 0.6289 - accuracy: 0.8217
Epoch 51/250
95/95 [==============================] - 0s 668us/step - loss: 0.6288 - accuracy: 0.8190
Epoch 52/250
95/95 [==============================] - ETA: 0s - loss: 0.5947 - accuracy: 0.84 - 0s 679us/step - loss: 0.6285 - accuracy: 0.8190
Epoch 53/250
95/95 [==============================] - 0s 700us/step - loss: 0.6284 - accuracy: 0.8190
Epoch 54/250
95/95 [==============================] - 0s 594us/step - loss: 0.6282 - accuracy: 0.8164
Epoch 55/250
95/95 [==============================] - 0s 573us/step - loss: 0.6282 - accuracy: 0.8203
Epoch 56/250
95/95 [==============================] - 0s 668us/step - loss: 0.6280 - accuracy: 0.8177
Epoch 57/250
95/95 [==============================] - 0s 700us/step - loss: 0.6277 - accuracy: 0.8243
Epoch 58/250
95/95 [==============================] - 0s 669us/step - loss: 0.6281 - accuracy: 0.8177
Epoch 59/250
95/95 [==============================] - 0s 583us/step - loss: 0.6276 - accuracy: 0.8190
Epoch 60/250
95/95 [==============================] - 0s 562us/step - loss: 0.6280 - accuracy: 0.8217
Epoch 61/250
95/95 [==============================] - 0s 573us/step - loss: 0.6271 - accuracy: 0.8203
Epoch 62/250
95/95 [==============================] - 0s 552us/step - loss: 0.6273 - accuracy: 0.8243
Epoch 63/250
95/95 [==============================] - 0s 626us/step - loss: 0.6273 - accuracy: 0.8190
Epoch 64/250
95/95 [==============================] - 0s 709us/step - loss: 0.6272 - accuracy: 0.8190
Epoch 65/250
95/95 [==============================] - 0s 690us/step - loss: 0.6269 - accuracy: 0.8190
Epoch 66/250
95/95 [==============================] - 0s 658us/step - loss: 0.6264 - accuracy: 0.8203
Epoch 67/250
95/95 [==============================] - 0s 626us/step - loss: 0.6265 - accuracy: 0.8217
Epoch 68/250
95/95 [==============================] - 0s 584us/step - loss: 0.6264 - accuracy: 0.8243
Epoch 69/250
95/95 [==============================] - 0s 562us/step - loss: 0.6261 - accuracy: 0.8217
Epoch 70/250
95/95 [==============================] - 0s 583us/step - loss: 0.6261 - accuracy: 0.8217
Epoch 71/250
95/95 [==============================] - 0s 541us/step - loss: 0.6259 - accuracy: 0.8230
Epoch 72/250
95/95 [==============================] - 0s 605us/step - loss: 0.6261 - accuracy: 0.8230
Epoch 73/250
95/95 [==============================] - 0s 679us/step - loss: 0.6256 - accuracy: 0.8230
Epoch 74/250
95/95 [==============================] - 0s 721us/step - loss: 0.6254 - accuracy: 0.8177
Epoch 75/250
95/95 [==============================] - 0s 679us/step - loss: 0.6257 - accuracy: 0.8230
Epoch 76/250
95/95 [==============================] - 0s 594us/step - loss: 0.6255 - accuracy: 0.8217
Epoch 77/250
95/95 [==============================] - 0s 552us/step - loss: 0.6251 - accuracy: 0.8217
Epoch 78/250
95/95 [==============================] - 0s 584us/step - loss: 0.6249 - accuracy: 0.8256
Epoch 79/250

95/95 [==============================] - 0s 562us/step - loss: 0.6249 - accuracy: 0.8190
Epoch 80/250
95/95 [==============================] - 0s 584us/step - loss: 0.6249 - accuracy: 0.8230
Epoch 81/250
95/95 [==============================] - 0s 573us/step - loss: 0.6246 - accuracy: 0.8203
Epoch 82/250
95/95 [==============================] - 0s 573us/step - loss: 0.6244 - accuracy: 0.8190
Epoch 83/250
95/95 [==============================] - 0s 552us/step - loss: 0.6243 - accuracy: 0.8217
Epoch 84/250
95/95 [==============================] - 0s 584us/step - loss: 0.6244 - accuracy: 0.8256
Epoch 85/250
95/95 [==============================] - 0s 552us/step - loss: 0.6240 - accuracy: 0.8230
Epoch 86/250
95/95 [==============================] - 0s 552us/step - loss: 0.6237 - accuracy: 0.8203
Epoch 87/250
95/95 [==============================] - 0s 552us/step - loss: 0.6237 - accuracy: 0.8230
Epoch 88/250
95/95 [==============================] - 0s 573us/step - loss: 0.6237 - accuracy: 0.8190
Epoch 89/250
95/95 [==============================] - 0s 562us/step - loss: 0.6233 - accuracy: 0.8177
Epoch 90/250
95/95 [==============================] - 0s 584us/step - loss: 0.6236 - accuracy: 0.8269
Epoch 91/250
95/95 [==============================] - 0s 573us/step - loss: 0.6235 - accuracy: 0.8243
Epoch 92/250
95/95 [==============================] - 0s 552us/step - loss: 0.6231 - accuracy: 0.8230
Epoch 93/250
95/95 [==============================] - 0s 541us/step - loss: 0.6228 - accuracy: 0.8164
Epoch 94/250
95/95 [==============================] - 0s 658us/step - loss: 0.6230 - accuracy: 0.8256
Epoch 95/250
95/95 [==============================] - 0s 679us/step - loss: 0.6229 - accuracy: 0.8217
Epoch 96/250
95/95 [==============================] - 0s 562us/step - loss: 0.6226 - accuracy: 0.8217
Epoch 97/250
95/95 [==============================] - 0s 584us/step - loss: 0.6223 - accuracy: 0.8217
Epoch 98/250
95/95 [==============================] - 0s 552us/step - loss: 0.6226 - accuracy: 0.8243
Epoch 99/250
95/95 [==============================] - 0s 562us/step - loss: 0.6223 - accuracy: 0.8177
Epoch 100/250
95/95 [==============================] - 0s 562us/step - loss: 0.6225 - accuracy: 0.8256
Epoch 101/250
95/95 [==============================] - 0s 552us/step - loss: 0.6219 - accuracy: 0.8217
Epoch 102/250
95/95 [==============================] - 0s 541us/step - loss: 0.6219 - accuracy: 0.8217
Epoch 103/250
95/95 [==============================] - 0s 573us/step - loss: 0.6220 - accuracy: 0.8243
Epoch 104/250
95/95 [==============================] - 0s 594us/step - loss: 0.6218 - accuracy: 0.8243
Epoch 105/250
95/95 [==============================] - 0s 806us/step - loss: 0.6218 - accuracy: 0.8243
Epoch 106/250
95/95 [==============================] - 0s 594us/step - loss: 0.6214 - accuracy: 0.8190
Epoch 107/250
95/95 [==============================] - 0s 615us/step - loss: 0.6217 - accuracy: 0.8256
Epoch 108/250
95/95 [==============================] - 0s 615us/step - loss: 0.6212 - accuracy: 0.8230
Epoch 109/250
95/95 [==============================] - 0s 594us/step - loss: 0.6211 - accuracy: 0.8177
Epoch 110/250
95/95 [==============================] - 0s 563us/step - loss: 0.6211 - accuracy: 0.8217
Epoch 111/250
95/95 [==============================] - 0s 541us/step - loss: 0.6212 - accuracy: 0.8243
Epoch 112/250
95/95 [==============================] - 0s 541us/step - loss: 0.6206 - accuracy: 0.8217
Epoch 113/250
95/95 [==============================] - 0s 562us/step - loss: 0.6205 - accuracy: 0.8190
Epoch 114/250
95/95 [==============================] - 0s 530us/step - loss: 0.6204 - accuracy: 0.8203
Epoch 115/250
95/95 [==============================] - 0s 552us/step - loss: 0.6208 - accuracy: 0.8217
Epoch 116/250
95/95 [==============================] - 0s 562us/step - loss: 0.6207 - accuracy: 0.8217
Epoch 117/250
95/95 [==============================] - 0s 562us/step - loss: 0.6202 - accuracy: 0.8256
Epoch 118/250
95/95 [==============================] - 0s 562us/step - loss: 0.6203 - accuracy: 0.8217
Epoch 119/250
95/95 [==============================] - 0s 552us/step - loss: 0.6201 - accuracy: 0.8230
Epoch 120/250
95/95 [==============================] - 0s 573us/step - loss: 0.6197 - accuracy: 0.8243
Epoch 121/250
95/95 [==============================] - 0s 573us/step - loss: 0.6201 - accuracy: 0.8203
Epoch 122/250
95/95 [==============================] - 0s 552us/step - loss: 0.6200 - accuracy: 0.8217
Epoch 123/250
95/95 [==============================] - 0s 573us/step - loss: 0.6197 - accuracy: 0.8269
Epoch 124/250
95/95 [==============================] - 0s 573us/step - loss: 0.6195 - accuracy: 0.8283
Epoch 125/250
95/95 [==============================] - 0s 562us/step - loss: 0.6191 - accuracy: 0.8243
Epoch 126/250
95/95 [==============================] - 0s 562us/step - loss: 0.6195 - accuracy: 0.8269
Epoch 127/250
95/95 [==============================] - 0s 584us/step - loss: 0.6199 - accuracy: 0.8269
Epoch 128/250
95/95 [==============================] - 0s 584us/step - loss: 0.6192 - accuracy: 0.8256
Epoch 129/250
95/95 [==============================] - 0s 552us/step - loss: 0.6195 - accuracy: 0.8256
Epoch 130/250
95/95 [==============================] - 0s 573us/step - loss: 0.6192 - accuracy: 0.8203
Epoch 131/250
95/95 [==============================] - 0s 594us/step - loss: 0.6193 - accuracy: 0.8256
Epoch 132/250
95/95 [==============================] - 0s 541us/step - loss: 0.6192 - accuracy: 0.8230
Epoch 133/250
95/95 [==============================] - 0s 562us/step - loss: 0.6192 - accuracy: 0.8243
Epoch 134/250
95/95 [==============================] - 0s 573us/step - loss: 0.6188 - accuracy: 0.8269
Epoch 135/250
95/95 [==============================] - 0s 552us/step - loss: 0.6187 - accuracy: 0.8296
Epoch 136/250
95/95 [==============================] - 0s 552us/step - loss: 0.6182 - accuracy: 0.8256
Epoch 137/250
95/95 [==============================] - 0s 563us/step - loss: 0.6186 - accuracy: 0.8283
Epoch 138/250
95/95 [==============================] - 0s 552us/step - loss: 0.6185 - accuracy: 0.8283
Epoch 139/250
95/95 [==============================] - 0s 562us/step - loss: 0.6181 - accuracy: 0.8283
Epoch 140/250
95/95 [==============================] - 0s 605us/step - loss: 0.6182 - accuracy: 0.8283
Epoch 141/250
95/95 [==============================] - 0s 552us/step - loss: 0.6189 - accuracy: 0.8269
Epoch 142/250
95/95 [==============================] - 0s 583us/step - loss: 0.6191 - accuracy: 0.8322
Epoch 143/250
95/95 [==============================] - 0s 584us/step - loss: 0.6186 - accuracy: 0.8269
Epoch 144/250
95/95 [==============================] - 0s 552us/step - loss: 0.6180 - accuracy: 0.8296
Epoch 145/250
95/95 [==============================] - 0s 541us/step - loss: 0.6181 - accuracy: 0.8283
Epoch 146/250
95/95 [==============================] - 0s 594us/step - loss: 0.6175 - accuracy: 0.8296
Epoch 147/250
95/95 [==============================] - 0s 541us/step - loss: 0.6178 - accuracy: 0.8256
Epoch 148/250
95/95 [==============================] - 0s 573us/step - loss: 0.6172 - accuracy: 0.8322
Epoch 149/250
95/95 [==============================] - 0s 562us/step - loss: 0.6169 - accuracy: 0.8296
Epoch 150/250
95/95 [==============================] - 0s 541us/step - loss: 0.6175 - accuracy: 0.8283
Epoch 151/250
95/95 [==============================] - 0s 562us/step - loss: 0.6173 - accuracy: 0.8309
Epoch 152/250
95/95 [==============================] - 0s 562us/step - loss: 0.6169 - accuracy: 0.8309
Epoch 153/250
95/95 [==============================] - 0s 562us/step - loss: 0.6170 - accuracy: 0.8309
Epoch 154/250
95/95 [==============================] - 0s 552us/step - loss: 0.6178 - accuracy: 0.8283
Epoch 155/250
95/95 [==============================] - 0s 552us/step - loss: 0.6170 - accuracy: 0.8309
Epoch 156/250
95/95 [==============================] - 0s 584us/step - loss: 0.6168 - accuracy: 0.8296
Epoch 157/250
95/95 [==============================] - 0s 562us/step - loss: 0.6171 - accuracy: 0.8296
Epoch 158/250

95/95 [==============================] - 0s 552us/step - loss: 0.6167 - accuracy: 0.8322
Epoch 159/250
95/95 [==============================] - 0s 552us/step - loss: 0.6163 - accuracy: 0.8269
Epoch 160/250
95/95 [==============================] - 0s 584us/step - loss: 0.6162 - accuracy: 0.8283
Epoch 161/250
95/95 [==============================] - 0s 541us/step - loss: 0.6173 - accuracy: 0.8269
Epoch 162/250
95/95 [==============================] - 0s 573us/step - loss: 0.6165 - accuracy: 0.8269
Epoch 163/250
95/95 [==============================] - 0s 594us/step - loss: 0.6165 - accuracy: 0.8296
Epoch 164/250
95/95 [==============================] - 0s 552us/step - loss: 0.6159 - accuracy: 0.8283
Epoch 165/250
95/95 [==============================] - 0s 541us/step - loss: 0.6161 - accuracy: 0.8256
Epoch 166/250
95/95 [==============================] - 0s 605us/step - loss: 0.6154 - accuracy: 0.8296
Epoch 167/250
95/95 [==============================] - 0s 552us/step - loss: 0.6161 - accuracy: 0.8283
Epoch 168/250
95/95 [==============================] - 0s 583us/step - loss: 0.6162 - accuracy: 0.8309
Epoch 169/250
95/95 [==============================] - 0s 562us/step - loss: 0.6157 - accuracy: 0.8269
Epoch 170/250
95/95 [==============================] - 0s 541us/step - loss: 0.6154 - accuracy: 0.8296
Epoch 171/250
95/95 [==============================] - 0s 562us/step - loss: 0.6149 - accuracy: 0.8283
Epoch 172/250
95/95 [==============================] - 0s 530us/step - loss: 0.6152 - accuracy: 0.8283
Epoch 173/250
95/95 [==============================] - 0s 573us/step - loss: 0.6150 - accuracy: 0.8322
Epoch 174/250
95/95 [==============================] - 0s 552us/step - loss: 0.6153 - accuracy: 0.8243
Epoch 175/250
95/95 [==============================] - 0s 573us/step - loss: 0.6151 - accuracy: 0.8336
Epoch 176/250
95/95 [==============================] - 0s 531us/step - loss: 0.6151 - accuracy: 0.8296
Epoch 177/250
95/95 [==============================] - 0s 573us/step - loss: 0.6149 - accuracy: 0.8309
Epoch 178/250
95/95 [==============================] - 0s 541us/step - loss: 0.6147 - accuracy: 0.8336
Epoch 179/250
95/95 [==============================] - 0s 552us/step - loss: 0.6145 - accuracy: 0.8296
Epoch 180/250
95/95 [==============================] - 0s 562us/step - loss: 0.6146 - accuracy: 0.8296
Epoch 181/250
95/95 [==============================] - 0s 584us/step - loss: 0.6143 - accuracy: 0.8296
Epoch 182/250
95/95 [==============================] - 0s 541us/step - loss: 0.6143 - accuracy: 0.8322
Epoch 183/250
95/95 [==============================] - 0s 552us/step - loss: 0.6142 - accuracy: 0.8309
Epoch 184/250
95/95 [==============================] - 0s 562us/step - loss: 0.6141 - accuracy: 0.8296
Epoch 185/250
95/95 [==============================] - 0s 552us/step - loss: 0.6143 - accuracy: 0.8269
Epoch 186/250
95/95 [==============================] - 0s 552us/step - loss: 0.6140 - accuracy: 0.8322
Epoch 187/250
95/95 [==============================] - 0s 552us/step - loss: 0.6140 - accuracy: 0.8283
Epoch 188/250
95/95 [==============================] - 0s 562us/step - loss: 0.6141 - accuracy: 0.8269
Epoch 189/250
95/95 [==============================] - 0s 541us/step - loss: 0.6140 - accuracy: 0.8309
Epoch 190/250
95/95 [==============================] - 0s 573us/step - loss: 0.6142 - accuracy: 0.8296
Epoch 191/250
95/95 [==============================] - 0s 615us/step - loss: 0.6136 - accuracy: 0.8349
Epoch 192/250
95/95 [==============================] - 0s 637us/step - loss: 0.6137 - accuracy: 0.8269
Epoch 193/250
95/95 [==============================] - 0s 637us/step - loss: 0.6137 - accuracy: 0.8296
Epoch 194/250
95/95 [==============================] - 0s 690us/step - loss: 0.6135 - accuracy: 0.8362
Epoch 195/250
95/95 [==============================] - 0s 668us/step - loss: 0.6133 - accuracy: 0.8283
Epoch 196/250
95/95 [==============================] - 0s 668us/step - loss: 0.6133 - accuracy: 0.8322
Epoch 197/250
95/95 [==============================] - 0s 679us/step - loss: 0.6137 - accuracy: 0.8296
Epoch 198/250
95/95 [==============================] - 0s 690us/step - loss: 0.6133 - accuracy: 0.8283
Epoch 199/250
95/95 [==============================] - 0s 679us/step - loss: 0.6130 - accuracy: 0.8309
Epoch 200/250
95/95 [==============================] - 0s 669us/step - loss: 0.6130 - accuracy: 0.8322
Epoch 201/250
95/95 [==============================] - 0s 690us/step - loss: 0.6126 - accuracy: 0.8362
Epoch 202/250
95/95 [==============================] - 0s 690us/step - loss: 0.6131 - accuracy: 0.8309
Epoch 203/250
95/95 [==============================] - 0s 700us/step - loss: 0.6136 - accuracy: 0.8296
Epoch 204/250
95/95 [==============================] - 0s 732us/step - loss: 0.6128 - accuracy: 0.8269
Epoch 205/250
95/95 [==============================] - 0s 690us/step - loss: 0.6131 - accuracy: 0.8283
Epoch 206/250
95/95 [==============================] - 0s 679us/step - loss: 0.6128 - accuracy: 0.8336
Epoch 207/250
95/95 [==============================] - 0s 679us/step - loss: 0.6134 - accuracy: 0.8296
Epoch 208/250
95/95 [==============================] - 0s 669us/step - loss: 0.6133 - accuracy: 0.8283
Epoch 209/250
95/95 [==============================] - 0s 679us/step - loss: 0.6125 - accuracy: 0.8283
Epoch 210/250
95/95 [==============================] - 0s 711us/step - loss: 0.6127 - accuracy: 0.8296
Epoch 211/250
95/95 [==============================] - 0s 711us/step - loss: 0.6125 - accuracy: 0.8256
Epoch 212/250
95/95 [==============================] - 0s 690us/step - loss: 0.6130 - accuracy: 0.8309
Epoch 213/250
95/95 [==============================] - 0s 700us/step - loss: 0.6125 - accuracy: 0.8296
Epoch 214/250
95/95 [==============================] - 0s 690us/step - loss: 0.6122 - accuracy: 0.8296
Epoch 215/250
95/95 [==============================] - 0s 668us/step - loss: 0.6130 - accuracy: 0.82830s - loss: 0.6113 - accuracy: 0.82
Epoch 216/250
95/95 [==============================] - 0s 679us/step - loss: 0.6122 - accuracy: 0.8269
Epoch 217/250
95/95 [==============================] - 0s 722us/step - loss: 0.6120 - accuracy: 0.8309
Epoch 218/250
95/95 [==============================] - 0s 806us/step - loss: 0.6122 - accuracy: 0.8283
Epoch 219/250
95/95 [==============================] - 0s 817us/step - loss: 0.6127 - accuracy: 0.8309
Epoch 220/250
95/95 [==============================] - 0s 817us/step - loss: 0.6127 - accuracy: 0.8322
Epoch 221/250
95/95 [==============================] - 0s 753us/step - loss: 0.6125 - accuracy: 0.8269
Epoch 222/250
95/95 [==============================] - 0s 711us/step - loss: 0.6123 - accuracy: 0.8322
Epoch 223/250
95/95 [==============================] - 0s 721us/step - loss: 0.6124 - accuracy: 0.8309
Epoch 224/250
95/95 [==============================] - 0s 785us/step - loss: 0.6116 - accuracy: 0.8296
Epoch 225/250
95/95 [==============================] - 0s 796us/step - loss: 0.6117 - accuracy: 0.8309
Epoch 226/250
95/95 [==============================] - 0s 817us/step - loss: 0.6112 - accuracy: 0.8283
Epoch 227/250
95/95 [==============================] - 0s 828us/step - loss: 0.6122 - accuracy: 0.8283
Epoch 228/250
95/95 [==============================] - 0s 786us/step - loss: 0.6117 - accuracy: 0.8283
Epoch 229/250
95/95 [==============================] - 0s 764us/step - loss: 0.6119 - accuracy: 0.8283
Epoch 230/250
95/95 [==============================] - 0s 743us/step - loss: 0.6117 - accuracy: 0.8336
Epoch 231/250
95/95 [==============================] - 0s 721us/step - loss: 0.6120 - accuracy: 0.8322
Epoch 232/250
95/95 [==============================] - 0s 785us/step - loss: 0.6112 - accuracy: 0.8349
Epoch 233/250
95/95 [==============================] - 0s 796us/step - loss: 0.6119 - accuracy: 0.8296
Epoch 234/250
95/95 [==============================] - 0s 849us/step - loss: 0.6122 - accuracy: 0.8309
Epoch 235/250
95/95 [==============================] - 0s 849us/step - loss: 0.6116 - accuracy: 0.8309
Epoch 236/250
95/95 [==============================] - 0s 807us/step - loss: 0.6115 - accuracy: 0.8283
Epoch 237/250

95/95 [==============================] - 0s 775us/step - loss: 0.6114 - accuracy: 0.8322
Epoch 238/250
95/95 [==============================] - 0s 700us/step - loss: 0.6119 - accuracy: 0.8296
Epoch 239/250
95/95 [==============================] - 0s 753us/step - loss: 0.6116 - accuracy: 0.8269
Epoch 240/250
95/95 [==============================] - 0s 711us/step - loss: 0.6116 - accuracy: 0.8296
Epoch 241/250
95/95 [==============================] - 0s 711us/step - loss: 0.6108 - accuracy: 0.8283
Epoch 242/250
95/95 [==============================] - 0s 668us/step - loss: 0.6112 - accuracy: 0.8322
Epoch 243/250
95/95 [==============================] - 0s 764us/step - loss: 0.6107 - accuracy: 0.8322
Epoch 244/250
95/95 [==============================] - 0s 817us/step - loss: 0.6118 - accuracy: 0.8309
Epoch 245/250
95/95 [==============================] - 0s 796us/step - loss: 0.6111 - accuracy: 0.8322
Epoch 246/250
95/95 [==============================] - 0s 764us/step - loss: 0.6115 - accuracy: 0.8296
Epoch 247/250
95/95 [==============================] - 0s 743us/step - loss: 0.6110 - accuracy: 0.8322
Epoch 248/250
95/95 [==============================] - 0s 711us/step - loss: 0.6108 - accuracy: 0.8243
Epoch 249/250
95/95 [==============================] - 0s 690us/step - loss: 0.6111 - accuracy: 0.8283
Epoch 250/250
95/95 [==============================] - 0s 679us/step - loss: 0.6105 - accuracy: 0.8309

In [21]:
from sklearn.metrics import average_precision_score
y_pred_train2 = np.round(ann_p.predict(X_train),0)
y_pred_test2 = np.round(ann_p.predict(X_test),0)
precision_test = average_precision_score(y_test, y_pred_test2)
precision_train = average_precision_score(y_train, y_pred_train2)
print(precision_train)
print(precision_test)

0.7092483580710709
0.6439358907505977

In [22]:
from sklearn.metrics import f1_score
f1_train = f1_score(y_train, y_pred_train2, average='macro')
f1_test = f1_score(y_test, y_pred_test2, average='macro')
print(f1_train)
print(f1_test)

0.8168029580770249
0.8191632928475032

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score, f1_score

# Create a svm Classifier#
clfrf=RandomForestClassifier(n_estimators=12, criterion="entropy", max_depth=None,
    min_samples_split=11, min_samples_leaf=1, min_weight_fraction_leaf=0.01, max_features='auto', max_leaf_nodes=10,
    min_impurity_decrease=0.035, min_impurity_split=0.1, bootstrap=True, oob_score=False, n_jobs=None,
    verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.04, max_samples=70, random_state = 262)

# Train the model using the training sets y_pred=clf.predict(X_test)
clfrf.fit(X_train,y_train)

# Predict the response for test dataset
y_pred_rf_train = clfrf.predict(X_train)
y_pred_rf_test = clfrf.predict(X_test)
print(metrics.precision_score(y_train, y_pred_rf_train))
print(metrics.precision_score(y_test, y_pred_rf_test))
f1_train = f1_score(y_train, y_pred_rf_train, average='macro')
f1_test = f1_score(y_test, y_pred_rf_test, average='macro')
print("train f1 score=", np.round(f1_train,3))
print("test f1 score=", np.round(f1_test,3))
Accuracy_train = accuracy_score(y_train, y_pred_rf_train)
Accuracy_test = accuracy_score(y_test, y_pred_rf_test)
print("train accuracy score=", np.round(Accuracy_train,3))
print("test accuracy score=", np.round(Accuracy_test,3))

0.8559322033898306
0.75
train f1 score= 0.808
test f1 score= 0.814
train accuracy score= 0.824
test accuracy score= 0.843

<ipython-input-23-9293d8fe7273>:12: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clfrf.fit(X_train,y_train)
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(
E:\Anaconda\lib\site-packages\sklearn\tree\_classes.py:316: FutureWarning: The min_impurity_split parameter is deprecated. Its default value has changed from 1e-7 to 0 in version 0.23, and it will be removed in 1.0 (renaming of 0.25). Use the min_impurity_decrease parameter instead.
  warnings.warn(

In [28]:
from sklearn import svm
#Create a svm Classifier
clf = svm.SVC(kernel='rbf', degree =2, gamma = 0.06, C = 10, max_iter=-1, random_state = 262, ) 

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred_svm_train = clf.predict(X_train)
y_pred_svm_test = clf.predict(X_test)
print(np.round(metrics.precision_score(y_train, y_pred_svm_train),3))
print(np.round(metrics.precision_score(y_test, y_pred_svm_test),3))
Accuracy_train = accuracy_score(y_train, y_pred_svm_train)
Accuracy_test = accuracy_score(y_test, y_pred_svm_test)
f1_train = f1_score(y_train, y_pred_svm_train, average='macro')
f1_test = f1_score(y_test, y_pred_svm_test, average='macro')
print("train f1 score=", np.round(f1_train,3))
print("test f1 score=", np.round(f1_test,3))
print("train accuracy score=", np.round(Accuracy_train,3))
print("test accuracy score=", np.round(Accuracy_test,3))

0.903
0.811
train f1 score= 0.827
test f1 score= 0.837
train accuracy score= 0.843
test accuracy score= 0.866

E:\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [ ]:
from sklearn import svm
#Create a svm Classifier
clf2 = svm.SVC(kernel='linear', degree = 3, gamma = 0.01, C = 1000, random_state = 262) # Linear Kernel

#Train the model using the training sets
clf2.fit(X_train, y_train)

#Predict the response for test dataset
y_pred_svm2_train = clf2.predict(X_train)
y_pred_svm2_test = clf2.predict(X_test)
print(metrics.precision_score(y_train, y_pred_svm2_train))
print(metrics.precision_score(y_test, y_pred_svm2_test))

E:\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [27]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
xgb = XGBClassifier(use_label_encoder=False, base_score=0.25, booster='gbtree', eta=0.3, max_depth=4, min_child_weight=20,
                    max_delta_step=0.5, subsample=0.6, colsample_bytree=1, colsample_bylevel=0.7, colsample_bynode=1, 
                    reg_lambda=1, reg_alpha=1, tree_method="approx", sketch_eps=0.1, scale_pos_weight=1.6, 
                    objective="binary:logitraw", gamma=0.8, n_estimators=10, rate_drop="0.01", skip_drop="0.8",
                    random_state = 262)
xgb.fit(X_train, y_train)
y_pred_xgb_train = xgb.predict(X_train)
y_pred_xgb_test = xgb.predict(X_test)

print("train precision=", np.round(metrics.precision_score(y_train, y_pred_xgb_train),3))
print("test precision=", np.round(metrics.precision_score(y_test, y_pred_xgb_test),3))
f1_train = f1_score(y_train, y_pred_xgb_train, average='macro')
f1_test = f1_score(y_test, y_pred_xgb_test, average='macro')
print("train f1 score=", np.round(f1_train,3))
print("test f1 score=", np.round(f1_test,3))
Accuracy_train = accuracy_score(y_train, y_pred_xgb_train)
Accuracy_test = accuracy_score(y_test, y_pred_xgb_test)
print("train accuracy score=", np.round(Accuracy_train,3))
print("test accuracy score=", np.round(Accuracy_test,3))

[16:41:53] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:573:
Parameters: { "rate_drop", "skip_drop" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[16:41:53] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.4.0, the default evaluation metric used with the objective 'binary:logitraw' was changed from 'auc' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
train precision= 0.896
test precision= 0.828
train f1 score= 0.778
test f1 score= 0.787
train accuracy score= 0.804
test accuracy score= 0.836

In [57]:
dft = pd.read_csv("test.csv", index_col=0)
dft

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [58]:
le = LabelEncoder()
dft['Embarked'] = le.fit_transform(dft['Embarked'])
dft['Sex'] = le.fit_transform(dft['Sex'])
dft

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,NaN,1
893,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,NaN,2
894,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,NaN,1
895,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,NaN,2
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,NaN,2
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",1,NaN,0,0,A.5. 3236,8.0500,NaN,2
1306,1,"Oliva y Ocana, Dona. Fermina",0,39.0,0,0,PC 17758,108.9000,C105,0
1307,3,"Saether, Mr. Simon Sivertsen",1,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,2
1308,3,"Ware, Mr. Frederick",1,NaN,0,0,359309,8.0500,NaN,2
1309,3,"Peter, Master. Michael J",1,NaN,1,1,2668,22.3583,NaN,0

In [59]:
dft = dft.apply(lambda col: LabelEncoder().fit_transform(dft["Embarked"]) if col.dtype == "object" else col)
dft.head(15)

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,1,1,34.5,0,0,1,7.8292,1,1
893,3,2,0,47.0,1,0,2,7.0000,2,2
894,2,1,1,62.0,0,0,1,9.6875,1,1
895,3,2,1,27.0,0,0,2,8.6625,2,2
896,3,2,0,22.0,1,1,2,12.2875,2,2
897,3,2,1,14.0,0,0,2,9.2250,2,2
898,3,1,0,30.0,0,0,1,7.6292,1,1
899,2,2,1,26.0,1,1,2,29.0000,2,2
900,3,0,0,18.0,0,0,0,7.2292,0,0
901,3,2,1,21.0,2,0,2,24.1500,2,2
902,3,2,1,NaN,0,0,2,7.8958,2,2
903,1,2,1,46.0,0,0,2,26.0000,2,2
904,1,2,0,23.0,1,0,2,82.2667,2,2
905,2,2,1,63.0,1,0,2,26.0000,2,2
906,1,2,0,47.0,1,0,2,61.1750,2,2

In [61]:
dft1 = dft.drop(columns={"Name","Cabin","Ticket"})
# split into input and output elements
data = dft1.values
ix = [i for i in range(data.shape[1]) if i != 9]
X, y = data[:, ix], data[:, 6]
# print total missing
print('Missing: %d' % sum(isnan(X).flatten()))
# define imputer
imputer = KNNImputer()
# fit on the dataset
imputer.fit(X)
# transform the dataset
dft1 = imputer.transform(X)
# print total missing
print('Missing: %d' % sum(isnan(dft1).flatten()))
dft1

Missing: 87
Missing: 0

array([[ 3.    ,  1.    , 34.5   , ...,  0.    ,  7.8292,  1.    ],
       [ 3.    ,  0.    , 47.    , ...,  0.    ,  7.    ,  2.    ],
       [ 2.    ,  1.    , 62.    , ...,  0.    ,  9.6875,  1.    ],
       ...,
       [ 3.    ,  1.    , 38.5   , ...,  0.    ,  7.25  ,  2.    ],
       [ 3.    ,  1.    , 32.1   , ...,  0.    ,  8.05  ,  2.    ],
       [ 3.    ,  1.    , 29.7   , ...,  1.    , 22.3583,  0.    ]])

In [62]:
dft1 = pd.DataFrame(dft1)
dft1

       0    1     2    3    4         5    6
0    3.0  1.0  34.5  0.0  0.0    7.8292  1.0
1    3.0  0.0  47.0  1.0  0.0    7.0000  2.0
2    2.0  1.0  62.0  0.0  0.0    9.6875  1.0
3    3.0  1.0  27.0  0.0  0.0    8.6625  2.0
4    3.0  0.0  22.0  1.0  1.0   12.2875  2.0
..   ...  ...   ...  ...  ...       ...  ...
413  3.0  1.0  32.1  0.0  0.0    8.0500  2.0
414  1.0  0.0  39.0  0.0  0.0  108.9000  0.0
415  3.0  1.0  38.5  0.0  0.0    7.2500  2.0
416  3.0  1.0  32.1  0.0  0.0    8.0500  2.0
417  3.0  1.0  29.7  1.0  1.0   22.3583  0.0

[418 rows x 7 columns]

In [64]:
dft1.columns = ["Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]
dftnew = dft1[["Pclass","Age","SibSp","Parch","Fare","Embarked","Sex"]]
print(dftnew.isnull().sum())
dftnew

Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Sex         0
dtype: int64

     Pclass   Age  SibSp  Parch      Fare  Embarked  Sex
0       3.0  34.5    0.0    0.0    7.8292       1.0  1.0
1       3.0  47.0    1.0    0.0    7.0000       2.0  0.0
2       2.0  62.0    0.0    0.0    9.6875       1.0  1.0
3       3.0  27.0    0.0    0.0    8.6625       2.0  1.0
4       3.0  22.0    1.0    1.0   12.2875       2.0  0.0
..      ...   ...    ...    ...       ...       ...  ...
413     3.0  32.1    0.0    0.0    8.0500       2.0  1.0
414     1.0  39.0    0.0    0.0  108.9000       0.0  0.0
415     3.0  38.5    0.0    0.0    7.2500       2.0  1.0
416     3.0  32.1    0.0    0.0    8.0500       2.0  1.0
417     3.0  29.7    1.0    1.0   22.3583       0.0  1.0

[418 rows x 7 columns]

In [65]:
sc = StandardScaler()
dftnew1 = sc.fit_transform(dftnew)
dftnew1

array([[ 0.87348191,  0.33966029, -0.49947002, ..., -0.49705948,
        -0.47091535,  0.75592895],
       [ 0.87348191,  1.30164075,  0.61699237, ..., -0.51192226,
         0.70076689, -1.32287566],
       [-0.31581919,  2.4560173 , -0.49947002, ..., -0.46375086,
        -0.47091535,  0.75592895],
       ...,
       [ 0.87348191,  0.64749404, -0.49947002, ..., -0.5074412 ,
         0.70076689,  0.75592895],
       [ 0.87348191,  0.15496005, -0.49947002, ..., -0.4931018 ,
         0.70076689,  0.75592895],
       [ 0.87348191, -0.0297402 ,  0.61699237, ..., -0.23663641,
        -1.64259759,  0.75592895]])

In [66]:
y_pred_clf = pd.DataFrame(np.round(clf.predict(dftnew1),0))
y_pred_clf.to_csv("svmclf.csv")